// var num:number=17;
// console.log("number:" + num);
//Generated by typescript 1.8.10
// var score1 = 50;
// score1++;
// console.log(score1);
// var num1:number=22;
// var num2:number=23;
// var result:boolean= num1 >num2 && num2< num1;
// console.log(result)
var temINCesus = 55;
var temInFer = (temINCesus * 9 / 5) + 32;
console.log("tem In F ", temInFer);
